# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

	config.vm.box = "debian/stretch64"
	config.vm.synced_folder ".", "/vagrant", type:"virtualbox"
	config.vm.provision "shell", path: "install-tools.sh"


	config.vm.define "git" do |git|
		git.vm.network "private_network", ip: "192.168.60.20" #test.2 - MIe en route d'une adresse ip 
		git.vm.provision "shell", path: "install-git-bare.sh" # acrivation d'un script à lancer 
		git.vm.provision "shell", path: "post-update.sh" # acrivation d'un script à lancer 
	end

	config.vm.define "web" do |web|
		web.vm.network "private_network", ip: "192.168.60.10" # test.estelle.local
		config.vm.provision "shell", path: "install-apache.sh"
	end
	
end




